name: laravel-queue-monitor
recipe: lemp
config:
  php: "8.2"
  composer_version: 2
  webroot: public
services:
  database:
    type: mariadb
    creds:
      user: web
      password: web
      database: web
  database-postgres:
    type: postgres
    creds:
      database: web
tooling:
  phpunit-mysql:
    service: appserver
    cmd: /app/vendor/bin/phpunit
    env:
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: web
      DB_USERNAME: web
      DB_PASSWORD: web
  phpunit-postgres:
    service: appserver
    cmd: /app/vendor/bin/phpunit
    env:
      DB_CONNECTION: pgsql
      DB_HOST: database-postgres
      DB_PORT: 5432
      DB_DATABASE: web
      DB_USERNAME: postgres
      DB_PASSWORD: ""
  phpunit-sqlite:
    service: appserver
    cmd: /app/vendor/bin/phpunit
    env:
      DB_CONNECTION: sqlite
      DB_DATABASE: "db.sqlite"
  phpcs:
    service: appserver
    cmd: /app/vendor/bin/php-cs-fixer
  phpstan:
    service: appserver
    cmd: /app/vendor/bin/phpstan
