name: Laravel

on:
  
  push:
    branches: 
      - '*'

  pull_request:
    branches:
      - '*'

jobs:
  test:
    
    strategy:
      matrix:
        composer_flags:
          - ""
          - --prefer-lowest

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2

    - name: Install dependencies
      run: composer update --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist ${{ matrix.composer_flags }}

    - name: Execute tests
      run: vendor/bin/phpunit
