name: Tests (SQLite)

on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.3", "8.4" ]
    name: "PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: composer update --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --prefer-stable

      - name: Create database
        run: touch db.sqlite

      - name: Execute tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: "db.sqlite"
